### ISSUE TITLE
Preguntas

### ISSUE THREAD

**Issue by Lucssiano** [pdepviernestm/2023-bienvenida-joacoZubiria#1]
Buenas Joaco! ¿Decis que vale la pena comprar la carrera de "Certified Tech Developer" de Digital House?

¿Que tal el lolapalooza, estuvo bueno?

Abrazo!

**Comment by joacoZubiria** [comment]
Hola Lucho, depende mucho, si tenes experiencia laboral previa en el mundo del desarrollo web dudo mucho que sirva, ya que se ven cosas de nivel técnico básico y muchos talleres de habilidades blandas, cosa que ya se labura en empresas IT, pero como entrada me parece excelente, un poco mucho cara jaja, generalmente dan becas del 50%, si ves alguna no dudes en aplicar.
Hablando del Lolla, fue una de las mejores experiencias que tuve, fui a ver a uno en especifico y se hizo de todo. Sin duda un evento imperdible.
