### ISSUE TITLE
Sugerencia 

### ISSUE THREAD

**Issue by Elias318** [pdepviernestm/2023-bienvenida-joacoZubiria#2]
Buenas , creo que deberias poner una foto de perfil por lo que dice la consigna . Un saludo !!

**Comment by joacoZubiria** [comment]
Hola Elías, con foto de perfil te referís a la de Github o en la presentación? Si es la segunda, está puesta, si es la primera, no ví en ningún lado que se necesite foto de perfil, aún así no lo había notado, gracias.

**Comment by Elias318** [comment]
Ahh acabo de darme cuenta que estabas en la pantalla del escenario jajajaaj . Muy buena. Saludos!
