### ISSUE TITLE
Pregunta 

### ISSUE THREAD

**Issue by Alex482xD** [pdepviernestm/2023-bienvenida-joacoZubiria#4]
Hola joaco, que tal todo bien ? Che alta foto que tenes, encima estas re cerca del escenario, copado. Que día del lollapalooza fuiste ? Y que artista fuiste a ver en especial ? Ultima, fue mejor de lo que esperabas ?

**Comment by joacoZubiria** [comment]
Hola Alex, como estas? Jajaja siii además salí en la feed del Instagram del artista. Fui los 3 días más el sideshow de Fred again.. y Skrillex. Fui a ver especialmente a Fred again.. es mi artista favorito desde hace mucho tiempo. Y contestando lo último, fue excelente, superó todo tipo de expectativa, una de las mejores experiencias lejos. Saludos y gracias por comentar!
